name: Build, Test and publish k8s-admission controller

on:
  push:
    branches: [main]
    paths:
      - "k8s-admission/**"
  pull_request:
    branches: [main]
    paths:
      - "k8s-admission/**"

permissions:
  contents: read

jobs:
  k8s-admission-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.23"

      - name: Run GoReleaser Test Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          workdir: k8s-admission
          args: release --clean --snapshot

      - name: Test
        working-directory: k8s-admission
        run: |
          tools/openssl-certs-gen-pki.sh
          test/build.sh
          ./admission-server $ADMISSION_ARGS &
          test/test.sh
        env:
          ALLOWED_IMAGES: docker.io
          HTTP_PROXY: http://example.com
          HTTPS_PROXY: https://example.com
          NO_PROXY: localhost
          CURL_ARGS: "--cacert tools/certificates/ca.pem --fail"
          ADMISSION_ARGS: --tls-cert-file tools/certificates/client1.pem --tls-private-key-file tools/certificates/client1.key

  k8s-admission-build-img:
    needs: [k8s-admission-test]
    uses: hegerdes/helper-suite/.github/workflows/reusable-docker-build.yml@main
    with:
      build-name: ${{ github.repository_owner }}/k8s-admission
      build-tags: latest
      push: ${{ startsWith(github.ref_name, 'main') }}
      scan-image: ${{ startsWith(github.ref_name, 'main') }}
      build-labels: MAINTAINER=${{ github.repository_owner }}
      build-dockerfile: k8s-admission/Dockerfile
      build-context: k8s-admission
      build-platforms: linux/amd64,linux/arm64
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PW: ${{ secrets.DOCKERHUB_TOKEN }}

  k8s-admission-build-chart:
    needs: [k8s-admission-test]
    uses: hegerdes/helper-suite/.github/workflows/reusable-helm-package.yml@main
    with:
      chart-sources-dir: k8s-admission/charts/k8s-admission
      chart-test-config-dir: k8s-admission/charts
      chart-publish: ${{ startsWith(github.ref_name, 'main') }}
      chart-release-version: 0.1.0
      publish-to-gh-pages: false
      chart-devel-version: ${{ !startsWith(github.ref_name, 'main') }}
      oci-registry-uri: registry-1.docker.io
      oci-registry-repo: ${{ github.repository_owner }}
      extra-commands-test: |
        helm repo add jetstack https://charts.jetstack.io --force-update && \
        helm upgrade --install cert-manager --namespace cert-manager --create-namespace --set crds.enabled=true jetstack/cert-manager
    secrets:
      OCI_REGISTRY_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      OCI_REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
